export const hotelTypesData = [
    "Business",
    "Airport",
    "Suite",
    "Resort",
    "Bed and Breakfast",
    "Timeshare",
    "Casino",
    "Holiday Resort",
    "Health Farm and Sanatorium",
    "Floating",
    "Floating",
    "Boutique",
    "Family",
    "Romanitic",
    "Hut",
    "All Inclusive",
    "Pet Friendly",
    "Bar",
]