export const hotelTypesData = [
    "Business",
    "Airport",
    "Suite",
    "Resort",
    "BednBreakfast",
    "Timeshare",
    "Casino",
    "Holiday Resort",
    "Health Farm",
    "Floating",
    "Boutique",
    "Family",
    "Romanitic",
    "Hut",
    "All Inclusive",
    "Pet Friendly",
]

export const hotelFacilitiesData = [
    "Free WiFi",
    "Gym",
    "Swimming Pool",
    "Restaurant",
    "Bar",
    "Spa",
    "Conference Rooms",
    "Parking",
    "24/7 Reception",
    "Room Service",
    "Laundry Service",
    "Air Conditioning",
    "Non-smoking Rooms",
    "Pet-friendly",
    "Airport Shuttle"
]